name: fastmdsimulation
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - openmm=8.*
  - openmmforcefields>=0.11
  - pdbfixer>=1.8
  - mdtraj>=1.9.9
  - pyyaml>=6
  - rich>=13
  - pip
  - pip:
      - fastmdanalysis>=1.0.0
